#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Apr 05, 2019 03:14:07 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global tch43
    tch43 = tk.StringVar()
    global tch44
    tch44 = tk.StringVar()
    global tch55
    tch55 = tk.StringVar()
    global tch56
    tch56 = tk.StringVar()
    global tch57
    tch57 = tk.StringVar()
    global tch58
    tch58 = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import bloom
    bloom.vp_start_gui()




